version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: adhar_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: adhar_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adhar_net

  redis:
    image: redis:7-alpine
    container_name: adhar_redis
    ports:
      - "6379:6379"
    networks:
      - adhar_net

networks:
  adhar_net:
    driver: bridge

volumes:
  postgres_data:
